particlesJS('top_page',{
    "particles":{
      "number":{
        "value":1500,
        "density":{
          "enable":false
        }
      },
      "shape":{
        "type":"image",
        "image":{
            "src":"./image/mrubyc_logo_01.png",
            "wide":50,
        },
        "stroke":{
          "width":1,
          "color":"#c70000"
        },
        "polygon": {
          "nb_sides":6
        }
      },
      "color":{
        "value":"#ffffff"
      },
      "opacity":{
        "value":0,
        "random":false,
        "anim":{
          "enable":false
        }
      },
      "size":{
        "value":2,
        "random":true,
        "anim":{
          "enable":false
        }
      },
      "line_linked":{
        "enable":false
      },
      "move":{
        "speed":5,
        "straight":false,
        "direction":"top",
        "out_mode":"out"
      }
    },
    "interactivity":{
      "detect_on":"canvas",
      "events":{
        "onhover":{
          "enable":true,
          "mode":"bubble"
        },
        "onclick":{
          "enable":false
        }
      },
      "modes":{
        "bubble":{
          "distance":100,
          "opacity":8,
          "duration":2,
          "speed":1
        }
      }
    },
    "retina_detect":true,
    "resize":true
  }
);